import { TreeBase } from "@/types/tree";

export const DEMO_TREE_CATALOG: TreeBase[] = [
  {
    id: "tree-neem",
    commonName: "Neem",
    scientificName: "Azadirachta indica",
    coolingScore: 94,
    carbonScore: 88,
    growthScore: 90,
    urbanSuitabilityScore: 95,
    pollutionToleranceScore: 85,
    droughtToleranceScore: 95,
    maintenanceScore: 90,
    waterRequirement: "Low",
    source: "HeatGuard Demo Dataset",
    dataStatus: "demo",
  },
  {
    id: "tree-peepal",
    commonName: "Peepal",
    scientificName: "Ficus religiosa",
    coolingScore: 98,
    carbonScore: 95,
    growthScore: 85,
    urbanSuitabilityScore: 70, // Roots can damage infrastructure
    pollutionToleranceScore: 90,
    droughtToleranceScore: 85,
    maintenanceScore: 80,
    waterRequirement: "Moderate",
    source: "HeatGuard Demo Dataset",
    dataStatus: "demo",
  },
  {
    id: "tree-arjun",
    commonName: "Arjun",
    scientificName: "Terminalia arjuna",
    coolingScore: 88,
    carbonScore: 85,
    growthScore: 95,
    urbanSuitabilityScore: 85,
    pollutionToleranceScore: 75,
    droughtToleranceScore: 70,
    maintenanceScore: 85,
    waterRequirement: "Moderate",
    source: "HeatGuard Demo Dataset",
    dataStatus: "demo",
  },
  {
    id: "tree-karanj",
    commonName: "Indian Beech (Karanj)",
    scientificName: "Millettia pinnata",
    coolingScore: 85,
    carbonScore: 80,
    growthScore: 92,
    urbanSuitabilityScore: 90,
    pollutionToleranceScore: 95,
    droughtToleranceScore: 90,
    maintenanceScore: 95,
    waterRequirement: "Low",
    source: "HeatGuard Demo Dataset",
    dataStatus: "demo",
  },
  {
    id: "tree-gulmohar",
    commonName: "Gulmohar",
    scientificName: "Delonix regia",
    coolingScore: 75,
    carbonScore: 70,
    growthScore: 95,
    urbanSuitabilityScore: 60, // Brittle branches, shallow roots
    pollutionToleranceScore: 70,
    droughtToleranceScore: 80,
    maintenanceScore: 75,
    waterRequirement: "Moderate",
    source: "HeatGuard Demo Dataset",
    dataStatus: "demo",
  }
];
